from __future__ import annotations

from typing import Protocol

from .models import AnalysisTaskMeta


class AnalysisRuntimeBackend(Protocol):
    async def register(self, meta: AnalysisTaskMeta) -> None: ...

    async def metadata(self, task_id: str) -> AnalysisTaskMeta | None: ...

    async def set_owner(self, task_id: str, user_id: int | None) -> None: ...

    async def owner(self, task_id: str) -> int | None: ...

    async def heartbeat(self, task_id: str, user_id: int | None = None) -> None: ...

    async def request_cancel(self, task_id: str) -> None: ...

    async def is_cancelled(self, task_id: str) -> bool: ...

    async def clear_cancel(self, task_id: str) -> None: ...

    async def clear_metadata(self, task_id: str, user_id: int | None = None) -> None: ...

    async def clear_owner(self, task_id: str) -> None: ...

    async def complete(self, task_id: str, user_id: int | None = None) -> None: ...

    async def active_tasks(self, user_id: int) -> list[AnalysisTaskMeta]: ...

    async def publish_cancel(self, task_id: str) -> None: ...
