import type { paths, components, operations } from './schema';

export type { paths, components, operations }

export type AnalysisRunRequest = components['schemas']['AnalysisRunRequest']
export type AnalysisRunResponse = components['schemas']['AnalysisRunResponse']
export type AnalysisResultRead = components['schemas']['AnalysisResultRead']
export type AnalysisListItem = components['schemas']['AnalysisListItem']
export type ChatMessageRead = components['schemas']['ChatMessageRead']
export type ChatMessageCreate = components['schemas']['ChatMessageCreate']
export type ActiveTaskRead = components['schemas']['ActiveTaskRead']
export type CancelTaskResponse = components['schemas']['CancelTaskResponse']
export type CostEstimateResponse = components['schemas']['CostEstimateResponse']
export type TimeTravelResponse = components['schemas']['TimeTravelResponse']
export type CheckpointItem = components['schemas']['CheckpointItem']
export type ABComparisonItem = components['schemas']['ABComparisonItem']
export type PerformanceResponse = components['schemas']['backend__schemas__analysis__PerformanceResponse']
export type PerformanceAttributionResponse = components['schemas']['PerformanceAttributionResponse']
export type MultiTickerRunResponse = components['schemas']['MultiTickerRunResponse']
export type MultiTickerListItem = components['schemas']['MultiTickerListItem']
export type MultiTickerResultRead = components['schemas']['MultiTickerResultRead']

export type UserRead = components['schemas']['UserRead']
export type PagePermissionsRead = components['schemas']['PagePermissionsRead']
export type ApiKeyProvidersResponse = components['schemas']['ApiKeyProvidersResponse']
export type SettingPermissionsResponse = components['schemas']['SettingPermissionsResponse']
export type UserPermissionsResponse = components['schemas']['UserPermissionsResponse']
export type AgentAccessUpdateResponse = components['schemas']['AgentAccessUpdateResponse']
export type ToolAccessUpdateResponse = components['schemas']['ToolAccessUpdateResponse']
export type ToolFieldAccessUpdateResponse = components['schemas']['ToolFieldAccessUpdateResponse']
export type UserAdminUpdate = components['schemas']['UserAdminUpdate']

export type PortfolioRead = components['schemas']['PortfolioRead']
export type HoldingRead = components['schemas']['HoldingRead']
export type OrderRead = components['schemas']['OrderRead']
export type SettingsRead = components['schemas']['SettingsRead']
export type SettingsUpdate = components['schemas']['SettingsUpdate']
export type LogRead = components['schemas']['LogRead']
export type AlertRead = components['schemas']['AlertRead']
export type AlertCreate = components['schemas']['AlertCreate']
export type AlertUpdate = components['schemas']['AlertUpdate']
export type PresetRead = components['schemas']['PresetRead']
export type PresetCreate = components['schemas']['PresetCreate']
export type PresetApplyResponse = components['schemas']['PresetApplyResponse']
export type PresetDeleteResponse = components['schemas']['PresetDeleteResponse']

export type SharedReportResponse = components['schemas']['SharedReportResponse']
export type ShareCreateResponse = components['schemas']['ShareCreateResponse']
export type DailySummaryResponse = components['schemas']['DailySummaryResponse']
export type ScreenResponse = components['schemas']['ScreenResponse']
export type WebhookDeliveryRead = components['schemas']['WebhookDeliveryRead']
export type MemoryStatusResponse = components['schemas']['MemoryStatusResponse']

export type PortfolioResponse = components['schemas']['PortfolioResponse']
export type APIOrderRequest = components['schemas']['APIOrderRequest']
export type OrderResponse = components['schemas']['OrderResponse']
export type ResetResponse = components['schemas']['ResetResponse']
export type BacktestResponse = components['schemas']['BacktestResponse']
export type PortfolioStatsResponse = components['schemas']['PortfolioStatsResponse']
export type RiskDashboardResponse = components['schemas']['RiskDashboardResponse']
export type RebalanceResponse = components['schemas']['RebalanceResponse']
export type JournalNoteResponse = components['schemas']['JournalNoteResponse']
export type JournalNoteReadResponse = components['schemas']['JournalNoteReadResponse']
export type JournalDebriefResponse = components['schemas']['JournalDebriefResponse']

export type AgentSettingsRead = components['schemas']['AgentSettingsRead']
export type AgentSettingsUpdate = components['schemas']['AgentSettingsUpdate']
export type ToolSettingsRead = components['schemas']['ToolSettingsRead']
export type ToolSettingsUpdate = components['schemas']['ToolSettingsUpdate']
export type SystemSettingsRead = components['schemas']['SystemSettingsRead']

export type AssistantHistoryItem = components['schemas']['AssistantHistoryItem']
export type AssistantChatResponse = components['schemas']['AssistantChatResponse']
export type FormulaAssistResponse = components['schemas']['FormulaAssistResponse']
export type PatternsResponse = components['schemas']['PatternsResponse']
export type CorrelationResponse = components['schemas']['CorrelationResponse']
export type EarningsCalendarResponse = components['schemas']['EarningsCalendarResponse']
export type SectorRotationResponse = components['schemas']['SectorRotationResponse']

export type MessageResponse = components['schemas']['MessageResponse']
export type DeleteResponse = components['schemas']['DeleteResponse']
export type OkResponse = components['schemas']['OkResponse']
