"""baseline

Revision ID: 89f1a049b357
Revises: 
Create Date: 2026-07-19 05:35:16.231170+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f1a049b357'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyst_report_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analyst_key', sa.String(length=30), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('data_hash', sa.String(length=64), nullable=False),
    sa.Column('analysis_result', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyst_report_cache_analyst_key'), 'analyst_report_cache', ['analyst_key'], unique=False)
    op.create_index(op.f('ix_analyst_report_cache_created_at'), 'analyst_report_cache', ['created_at'], unique=False)
    op.create_index(op.f('ix_analyst_report_cache_data_hash'), 'analyst_report_cache', ['data_hash'], unique=False)
    op.create_index(op.f('ix_analyst_report_cache_ticker'), 'analyst_report_cache', ['ticker'], unique=False)
    op.create_table('news_analysis_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('articles_hash', sa.String(length=64), nullable=False),
    sa.Column('analysis_result', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_analysis_cache_articles_hash'), 'news_analysis_cache', ['articles_hash'], unique=False)
    op.create_index(op.f('ix_news_analysis_cache_created_at'), 'news_analysis_cache', ['created_at'], unique=False)
    op.create_index(op.f('ix_news_analysis_cache_ticker'), 'news_analysis_cache', ['ticker'], unique=False)
    op.create_table('news_cache',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('news_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trading_mode', sa.String(length=20), nullable=False),
    sa.Column('active_broker', sa.String(length=50), nullable=False),
    sa.Column('active_data_vendor', sa.String(length=50), nullable=False),
    sa.Column('data_vendor_core_stock', sa.String(length=50), nullable=False),
    sa.Column('data_vendor_technicals', sa.String(length=50), nullable=False),
    sa.Column('data_vendor_fundamentals', sa.String(length=50), nullable=False),
    sa.Column('data_vendor_news', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('api_keys_enc', sa.Text(), nullable=True),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('agent_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('agent_key', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'user_id', 'agent_key', name='uq_agent_settings_scope_user_agent')
    )
    op.create_index(op.f('ix_agent_settings_agent_key'), 'agent_settings', ['agent_key'], unique=False)
    op.create_index(op.f('ix_agent_settings_scope'), 'agent_settings', ['scope'], unique=False)
    op.create_index(op.f('ix_agent_settings_user_id'), 'agent_settings', ['user_id'], unique=False)
    op.create_table('agent_tool_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tool_key', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'user_id', 'tool_key', name='uq_agent_tool_settings_scope_user_tool')
    )
    op.create_index(op.f('ix_agent_tool_settings_scope'), 'agent_tool_settings', ['scope'], unique=False)
    op.create_index(op.f('ix_agent_tool_settings_tool_key'), 'agent_tool_settings', ['tool_key'], unique=False)
    op.create_index(op.f('ix_agent_tool_settings_user_id'), 'agent_tool_settings', ['user_id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('trade_date', sa.String(length=20), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('signal', sa.String(length=50), nullable=True),
    sa.Column('market_report', sa.Text(), nullable=False),
    sa.Column('sentiment_report', sa.Text(), nullable=False),
    sa.Column('news_report', sa.Text(), nullable=False),
    sa.Column('fundamentals_report', sa.Text(), nullable=False),
    sa.Column('macro_report', sa.Text(), nullable=False),
    sa.Column('options_report', sa.Text(), nullable=False),
    sa.Column('quant_report', sa.Text(), nullable=False),
    sa.Column('earnings_report', sa.Text(), nullable=False),
    sa.Column('insider_report', sa.Text(), nullable=False),
    sa.Column('ownership_report', sa.Text(), nullable=False),
    sa.Column('ratings_report', sa.Text(), nullable=False),
    sa.Column('short_interest_report', sa.Text(), nullable=False),
    sa.Column('valuation_report', sa.Text(), nullable=False),
    sa.Column('catalyst_report', sa.Text(), nullable=False),
    sa.Column('review_report', sa.Text(), nullable=False),
    sa.Column('synthesis_report', sa.Text(), nullable=False),
    sa.Column('audit_report', sa.Text(), nullable=False),
    sa.Column('agent_qa_report', sa.Text(), nullable=False),
    sa.Column('investment_plan', sa.Text(), nullable=False),
    sa.Column('trader_plan', sa.Text(), nullable=False),
    sa.Column('final_decision', sa.Text(), nullable=False),
    sa.Column('reflection', sa.Text(), nullable=False),
    sa.Column('bull_history', sa.JSON(), nullable=True),
    sa.Column('bear_history', sa.JSON(), nullable=True),
    sa.Column('investment_debate_history', sa.JSON(), nullable=True),
    sa.Column('risk_debate_history', sa.JSON(), nullable=True),
    sa.Column('judge_decision', sa.Text(), nullable=False),
    sa.Column('trader_proposal_json', sa.Text(), nullable=False),
    sa.Column('chart_annotations', sa.JSON(), nullable=True),
    sa.Column('risk_metrics', sa.JSON(), nullable=True),
    sa.Column('quality', sa.JSON(), nullable=True),
    sa.Column('degraded', sa.Integer(), nullable=False),
    sa.Column('failed_agents', sa.JSON(), nullable=True),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('tool_calls', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('llm_provider', sa.String(length=50), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('preset_name', sa.String(length=100), nullable=True),
    sa.Column('triggered_by', sa.String(length=20), nullable=False),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raw_return', sa.Float(), nullable=True),
    sa.Column('alpha_return', sa.Float(), nullable=True),
    sa.Column('holding_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_created_at'), 'analysis_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_results_status'), 'analysis_results', ['status'], unique=False)
    op.create_index(op.f('ix_analysis_results_task_id'), 'analysis_results', ['task_id'], unique=True)
    op.create_index(op.f('ix_analysis_results_ticker'), 'analysis_results', ['ticker'], unique=False)
    op.create_index('ix_analysis_results_trade_date', 'analysis_results', ['trade_date'], unique=False)
    op.create_index(op.f('ix_analysis_results_user_id'), 'analysis_results', ['user_id'], unique=False)
    op.create_index('ix_analysis_results_user_ticker', 'analysis_results', ['user_id', 'ticker'], unique=False)
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cron_enabled', sa.Boolean(), nullable=False),
    sa.Column('cron_schedule', sa.String(length=100), nullable=False),
    sa.Column('price_tolerance_pct', sa.Float(), nullable=False),
    sa.Column('watchlist', sa.Text(), nullable=False),
    sa.Column('output_language', sa.String(length=50), nullable=False),
    sa.Column('llm_provider', sa.String(length=50), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('fallback_llm_provider', sa.String(length=50), nullable=True),
    sa.Column('fallback_llm_model', sa.String(length=100), nullable=True),
    sa.Column('investor_persona', sa.String(length=50), nullable=False),
    sa.Column('analyst_concurrency_limit', sa.Integer(), nullable=False),
    sa.Column('max_recur_limit', sa.Integer(), nullable=False),
    sa.Column('benchmark_ticker', sa.String(length=20), nullable=True),
    sa.Column('openai_reasoning_effort', sa.String(length=20), nullable=True),
    sa.Column('anthropic_effort', sa.String(length=20), nullable=True),
    sa.Column('google_thinking_level', sa.String(length=20), nullable=True),
    sa.Column('max_debate_rounds', sa.Integer(), nullable=False),
    sa.Column('max_risk_rounds', sa.Integer(), nullable=False),
    sa.Column('max_position_size_pct', sa.Float(), nullable=False),
    sa.Column('max_risk_per_trade_pct', sa.Float(), nullable=False),
    sa.Column('strict_stop_loss_mode', sa.Boolean(), nullable=False),
    sa.Column('correlation_risk_enabled', sa.Boolean(), nullable=False),
    sa.Column('quality_gate_enabled', sa.Boolean(), nullable=False),
    sa.Column('drawdown_breaker_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_portfolio_drawdown_pct', sa.Float(), nullable=False),
    sa.Column('node_retry_attempts', sa.Integer(), nullable=False),
    sa.Column('node_retry_base_delay', sa.Float(), nullable=False),
    sa.Column('node_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('tool_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('circuit_breaker_threshold', sa.Integer(), nullable=False),
    sa.Column('circuit_breaker_cooldown', sa.Integer(), nullable=False),
    sa.Column('stall_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('webhook_enabled', sa.Boolean(), nullable=False),
    sa.Column('webhook_events', sa.Text(), nullable=False),
    sa.Column('active_preset_name', sa.String(length=100), nullable=True),
    sa.Column('memory_store', sa.String(length=20), nullable=False),
    sa.Column('pinecone_index', sa.String(length=100), nullable=False),
    sa.Column('pinecone_cloud', sa.String(length=20), nullable=False),
    sa.Column('pinecone_region', sa.String(length=30), nullable=False),
    sa.Column('memory_embedder', sa.String(length=20), nullable=False),
    sa.Column('pinecone_embed_model', sa.String(length=60), nullable=False),
    sa.Column('memory_openai_embed_model', sa.String(length=60), nullable=False),
    sa.Column('memory_ollama_embed_model', sa.String(length=60), nullable=False),
    sa.Column('agent_qa_enabled', sa.Boolean(), nullable=False),
    sa.Column('anthropic_prompt_caching', sa.Boolean(), nullable=False),
    sa.Column('max_report_chars_in_prompts', sa.Integer(), nullable=False),
    sa.Column('max_debate_history_chars', sa.Integer(), nullable=False),
    sa.Column('max_tool_output_chars', sa.Integer(), nullable=False),
    sa.Column('analyst_prefilter_enabled', sa.Boolean(), nullable=False),
    sa.Column('analyst_prefilter_min_samples', sa.Integer(), nullable=False),
    sa.Column('analyst_prefilter_max_win_rate', sa.Float(), nullable=False),
    sa.Column('memory_recall_count', sa.Integer(), nullable=False),
    sa.Column('summary_only_mode', sa.Boolean(), nullable=False),
    sa.Column('news_article_limit', sa.Integer(), nullable=False),
    sa.Column('global_news_article_limit', sa.Integer(), nullable=False),
    sa.Column('global_news_lookback_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_settings_user_id'), 'app_settings', ['user_id'], unique=False)
    op.create_table('assistant_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistant_messages_user_id'), 'assistant_messages', ['user_id'], unique=False)
    op.create_table('config_presets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_presets_user_id'), 'config_presets', ['user_id'], unique=False)
    op.create_table('market_daily_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('tickers', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_daily_summaries_date'), 'market_daily_summaries', ['date'], unique=False)
    op.create_index(op.f('ix_market_daily_summaries_user_id'), 'market_daily_summaries', ['user_id'], unique=False)
    op.create_table('multi_ticker_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('trade_date', sa.String(length=20), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('tickers', sa.Text(), nullable=False),
    sa.Column('analysis_ids', sa.Text(), nullable=False),
    sa.Column('super_portfolio_report', sa.Text(), nullable=False),
    sa.Column('triggered_by', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multi_ticker_analyses_created_at'), 'multi_ticker_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_multi_ticker_analyses_user_id'), 'multi_ticker_analyses', ['user_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('broker', sa.String(length=50), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('cash_available', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('margin_used', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mode', name='uq_portfolio_user_mode')
    )
    op.create_index(op.f('ix_portfolios_mode'), 'portfolios', ['mode'], unique=False)
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('price_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('alert_type', sa.String(length=20), server_default='price', nullable=False),
    sa.Column('condition', sa.String(length=10), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('auto_analyze', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_alerts_enabled_triggered', 'price_alerts', ['enabled', 'triggered_at'], unique=False)
    op.create_index(op.f('ix_price_alerts_ticker'), 'price_alerts', ['ticker'], unique=False)
    op.create_index(op.f('ix_price_alerts_user_id'), 'price_alerts', ['user_id'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_created_at'), 'system_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_index(op.f('ix_system_logs_source'), 'system_logs', ['source'], unique=False)
    op.create_index('ix_system_logs_user_created', 'system_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_system_logs_user_id'), 'system_logs', ['user_id'], unique=False)
    op.create_table('user_agent_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_key', sa.String(length=100), nullable=False),
    sa.Column('can_run', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'agent_key', name='uq_user_agent_access_user_agent')
    )
    op.create_index(op.f('ix_user_agent_access_agent_key'), 'user_agent_access', ['agent_key'], unique=False)
    op.create_index(op.f('ix_user_agent_access_user_id'), 'user_agent_access', ['user_id'], unique=False)
    op.create_table('user_page_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('page_key', sa.String(length=50), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'page_key', name='uq_user_page')
    )
    op.create_table('user_personas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_user_persona_user_key')
    )
    op.create_index(op.f('ix_user_personas_user_id'), 'user_personas', ['user_id'], unique=False)
    op.create_table('user_setting_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(length=50), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'setting_key', name='uq_user_setting')
    )
    op.create_table('user_tool_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tool_key', sa.String(length=100), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_use', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('can_enable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tool_key', name='uq_user_tool_access_user_tool')
    )
    op.create_index(op.f('ix_user_tool_access_tool_key'), 'user_tool_access', ['tool_key'], unique=False)
    op.create_index(op.f('ix_user_tool_access_user_id'), 'user_tool_access', ['user_id'], unique=False)
    op.create_table('user_tool_field_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tool_key', sa.String(length=100), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tool_key', 'field_key', name='uq_user_tool_field_access_user_tool_field')
    )
    op.create_index(op.f('ix_user_tool_field_access_field_key'), 'user_tool_field_access', ['field_key'], unique=False)
    op.create_index(op.f('ix_user_tool_field_access_tool_key'), 'user_tool_field_access', ['tool_key'], unique=False)
    op.create_index(op.f('ix_user_tool_field_access_user_id'), 'user_tool_field_access', ['user_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_user_id'), 'webhook_deliveries', ['user_id'], unique=False)
    op.create_table('analysis_chats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_chats_analysis_id'), 'analysis_chats', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_analysis_chats_created_at'), 'analysis_chats', ['created_at'], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('avg_buy_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('side', sa.String(length=5), nullable=False),
    sa.Column('leverage', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('margin_used', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('borrowed_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('liquidation_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('interest_accrued', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('take_profit', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'ticker', name='uq_holding_portfolio_ticker')
    )
    op.create_index('ix_holdings_portfolio_ticker', 'holdings', ['portfolio_id', 'ticker'], unique=False)
    op.create_index(op.f('ix_holdings_ticker'), 'holdings', ['ticker'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('broker', sa.String(length=50), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('quantity_requested', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('quantity_filled', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('price_per_share', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('commission', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('leverage', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('side', sa.String(length=5), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('ai_signal', sa.String(length=50), nullable=False),
    sa.Column('ai_reasoning', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_results.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_analysis_id'), 'orders', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_portfolio_id'), 'orders', ['portfolio_id'], unique=False)
    op.create_index('ix_orders_portfolio_ticker', 'orders', ['portfolio_id', 'ticker'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_ticker'), 'orders', ['ticker'], unique=False)
    op.create_table('shared_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_results.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_reports_analysis_id'), 'shared_reports', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_shared_reports_token'), 'shared_reports', ['token'], unique=True)
    op.create_table('trade_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('ai_debrief', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_notes_order_id'), 'trade_notes', ['order_id'], unique=False)
    op.create_index(op.f('ix_trade_notes_user_id'), 'trade_notes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_notes_user_id'), table_name='trade_notes')
    op.drop_index(op.f('ix_trade_notes_order_id'), table_name='trade_notes')
    op.drop_table('trade_notes')
    op.drop_index(op.f('ix_shared_reports_token'), table_name='shared_reports')
    op.drop_index(op.f('ix_shared_reports_analysis_id'), table_name='shared_reports')
    op.drop_table('shared_reports')
    op.drop_index(op.f('ix_orders_ticker'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index('ix_orders_portfolio_ticker', table_name='orders')
    op.drop_index(op.f('ix_orders_portfolio_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_analysis_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_holdings_ticker'), table_name='holdings')
    op.drop_index('ix_holdings_portfolio_ticker', table_name='holdings')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_analysis_chats_created_at'), table_name='analysis_chats')
    op.drop_index(op.f('ix_analysis_chats_analysis_id'), table_name='analysis_chats')
    op.drop_table('analysis_chats')
    op.drop_index(op.f('ix_webhook_deliveries_user_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_user_tool_field_access_user_id'), table_name='user_tool_field_access')
    op.drop_index(op.f('ix_user_tool_field_access_tool_key'), table_name='user_tool_field_access')
    op.drop_index(op.f('ix_user_tool_field_access_field_key'), table_name='user_tool_field_access')
    op.drop_table('user_tool_field_access')
    op.drop_index(op.f('ix_user_tool_access_user_id'), table_name='user_tool_access')
    op.drop_index(op.f('ix_user_tool_access_tool_key'), table_name='user_tool_access')
    op.drop_table('user_tool_access')
    op.drop_table('user_setting_permissions')
    op.drop_index(op.f('ix_user_personas_user_id'), table_name='user_personas')
    op.drop_table('user_personas')
    op.drop_table('user_page_permissions')
    op.drop_index(op.f('ix_user_agent_access_user_id'), table_name='user_agent_access')
    op.drop_index(op.f('ix_user_agent_access_agent_key'), table_name='user_agent_access')
    op.drop_table('user_agent_access')
    op.drop_index(op.f('ix_system_logs_user_id'), table_name='system_logs')
    op.drop_index('ix_system_logs_user_created', table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_source'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_created_at'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_price_alerts_user_id'), table_name='price_alerts')
    op.drop_index(op.f('ix_price_alerts_ticker'), table_name='price_alerts')
    op.drop_index('ix_price_alerts_enabled_triggered', table_name='price_alerts')
    op.drop_table('price_alerts')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_mode'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_multi_ticker_analyses_user_id'), table_name='multi_ticker_analyses')
    op.drop_index(op.f('ix_multi_ticker_analyses_created_at'), table_name='multi_ticker_analyses')
    op.drop_table('multi_ticker_analyses')
    op.drop_index(op.f('ix_market_daily_summaries_user_id'), table_name='market_daily_summaries')
    op.drop_index(op.f('ix_market_daily_summaries_date'), table_name='market_daily_summaries')
    op.drop_table('market_daily_summaries')
    op.drop_index(op.f('ix_config_presets_user_id'), table_name='config_presets')
    op.drop_table('config_presets')
    op.drop_index(op.f('ix_assistant_messages_user_id'), table_name='assistant_messages')
    op.drop_table('assistant_messages')
    op.drop_index(op.f('ix_app_settings_user_id'), table_name='app_settings')
    op.drop_table('app_settings')
    op.drop_index('ix_analysis_results_user_ticker', table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_user_id'), table_name='analysis_results')
    op.drop_index('ix_analysis_results_trade_date', table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_ticker'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_task_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_status'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_created_at'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_agent_tool_settings_user_id'), table_name='agent_tool_settings')
    op.drop_index(op.f('ix_agent_tool_settings_tool_key'), table_name='agent_tool_settings')
    op.drop_index(op.f('ix_agent_tool_settings_scope'), table_name='agent_tool_settings')
    op.drop_table('agent_tool_settings')
    op.drop_index(op.f('ix_agent_settings_user_id'), table_name='agent_settings')
    op.drop_index(op.f('ix_agent_settings_scope'), table_name='agent_settings')
    op.drop_index(op.f('ix_agent_settings_agent_key'), table_name='agent_settings')
    op.drop_table('agent_settings')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_table('news_cache')
    op.drop_index(op.f('ix_news_analysis_cache_ticker'), table_name='news_analysis_cache')
    op.drop_index(op.f('ix_news_analysis_cache_created_at'), table_name='news_analysis_cache')
    op.drop_index(op.f('ix_news_analysis_cache_articles_hash'), table_name='news_analysis_cache')
    op.drop_table('news_analysis_cache')
    op.drop_index(op.f('ix_analyst_report_cache_ticker'), table_name='analyst_report_cache')
    op.drop_index(op.f('ix_analyst_report_cache_data_hash'), table_name='analyst_report_cache')
    op.drop_index(op.f('ix_analyst_report_cache_created_at'), table_name='analyst_report_cache')
    op.drop_index(op.f('ix_analyst_report_cache_analyst_key'), table_name='analyst_report_cache')
    op.drop_table('analyst_report_cache')
    # ### end Alembic commands ###
