/**
 * Frozen snapshot of the export section headings as they were before the
 * registry consolidation, in both languages.
 *
 * Exported documents are a user-facing artefact; a refactor must not silently
 * reword their headings. Any intentional change to this table should be a
 * deliberate edit here, not a side effect.
 */

export const EXPECTED_EXPORT_ORDER = [
  'final_decision',
  'investment_plan',
  'trader_plan',
  'market_report',
  'fundamentals_report',
  'news_report',
  'sentiment_report',
  'macro_report',
  'options_report',
  'quant_report',
  'earnings_report',
  'insider_report',
  'ownership_report',
  'ratings_report',
  'short_interest_report',
  'valuation_report',
  'catalyst_report',
  'review_report',
  'synthesis_report',
  'audit_report',
  'agent_qa_report',
  'bull_history',
  'bear_history',
  'investment_debate_history',
  'risk_debate_history',
  'judge_decision',
] as const

export const EXPECTED_EXPORT_LABELS: Record<'en' | 'tr', Record<string, string>> = {
  en: {
    final_decision: 'Final Decision (Portfolio Manager)',
    investment_plan: 'Research Evidence Summary',
    trader_plan: 'Legacy Trader Proposal (historical only)',
    market_report: 'Market Analysis',
    fundamentals_report: 'Fundamentals',
    news_report: 'News Analysis',
    sentiment_report: 'Sentiment Analysis',
    macro_report: 'Macro Analysis',
    options_report: 'Options Analysis',
    quant_report: 'Quantitative Analysis',
    earnings_report: 'Earnings Analysis',
    insider_report: 'Insider Activity',
    ownership_report: 'Institutional Ownership',
    ratings_report: 'Analyst Ratings',
    short_interest_report: 'Short Interest',
    valuation_report: 'Valuation Comparison',
    catalyst_report: 'Upcoming Catalysts',
    review_report: 'Review',
    synthesis_report: 'Synthesis',
    audit_report: 'Audit',
    agent_qa_report: 'Agent Cross-Examination',
    bull_history: 'Bull Arguments',
    bear_history: 'Bear Arguments',
    investment_debate_history: 'Investment Debate',
    risk_debate_history: 'Risk Debate',
    judge_decision: 'Judge Decision',
  },
  tr: {
    final_decision: 'Nihai Karar (Portfolio Manager)',
    investment_plan: 'Araştırma Kanıt Özeti',
    trader_plan: 'Eski Trader Önerisi (yalnız geçmiş kayıt)',
    market_report: 'Piyasa Analizi',
    fundamentals_report: 'Temel Analiz',
    news_report: 'Haber Analizi',
    sentiment_report: 'Duygu Analizi',
    macro_report: 'Makro Analiz',
    options_report: 'Opsiyon Analizi',
    quant_report: 'Kantitatif Analiz',
    earnings_report: 'Kazanç Analizi',
    insider_report: 'İçeriden İşlem',
    ownership_report: 'Kurumsal Sahiplik',
    ratings_report: 'Analist Tavsiyeleri',
    short_interest_report: 'Açığa Satış',
    valuation_report: 'Değerleme Karşılaştırması',
    catalyst_report: 'Yaklaşan Katalizörler',
    review_report: 'Performans İnceleme',
    synthesis_report: 'Sentez',
    audit_report: 'Denetim',
    agent_qa_report: 'Ajan Çapraz Sorgu',
    bull_history: 'Boğa Argümanları',
    bear_history: 'Ayı Argümanları',
    investment_debate_history: 'Yatırım Tartışması',
    risk_debate_history: 'Risk Tartışması',
    judge_decision: 'Hakem Kararı',
  },
}
